server:
  port: 18080
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/performance
    username: root
    password: password
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    elasticsearch:
      repositories:
        enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://127.0.0.1:13306/performance
    user: root
    password: password
  elasticsearch:
    uris: https://localhost:19200
    username: elastic
    password: "@elastic"
logging:
  level:
    root: debug